### PR TITLE
Single node cluster will commit noop entry immediately

### LINKED ISSUE #28: Fix NOOP entry handling
https://github.com/RedisLabs/raft/blob/99e3d4a6e2a6d1d178d6bd125654ac3cedfe492b/src/raft_server.c#L178

Single node cluster should commit noop entry immediately without waiting appendresp. Currently, it doesn't commit noop entry. Meanwhile, if a client sends a read-only request, request hangs as it waits until noop entry is committed.

### PR DESCRIPTION
**Pull request by tezc**
Before the fix, if there is no new write request, read requests will hang as they will wait noop entry to be committed forever.
After the fix, single node cluster will commit noop entry immediately. 

fixes #28

### CODE REVIEW

**Comment by sjpotter** [comment]
I'd think recv_entry would have avoided the need for this, as it would have done it by itself.  that's my only concern (i.e. duplicative), but if we dont want to go with recv_entry, I'm fine with this.

**Comment by tezc** [comment]
@sjpotter This is the simplest solution for now. 

If we don't write noop entry for term=1, we won't call raft_recv and we won't send append entries. Normally we should send append entries immediately when we become a leader. If we send it inside the loop when we are adjusting next_indexes, we will be sending multiple appendreqs(another one inside raft_recv()) for term > 1 etc.. 

Best solution would be writing noop unconditionally but that causes more issues as you know. Also, there are some tests that makes some assumptions about these issues. 

I think we can come back and refactor later, as there are multiple places to refactor. What do you think?

**Comment by sjpotter** [comment]
I was wondering if we could just do

set leader
if (term > 1) {
  raft_recv_entry(noop);
}

i.e. similiar logic to existing, but not needing to code the commit / send_append_entry stuff here, as would be handled by recv_entry itself.

i.e. if single node, recv_entry will commit.  if multiple nodes, it won't, and will contact them (or should? we would have to examine recv_entry.

this is "simpler" to change and fix, so I'm ok with it for now, I'm just wondering for what way forward.

**Comment by tezc** [comment]
I'm talking about this example, I took your code and only added if (term > 1) check as we discussed. For that code, when term == 1, we won't be sending appendreqs as we don't call recv_entry(). We should send "one appendreq" when we become the leader either empty or with noop entry in it. 

Best way would be sending noop unconditionally but you know it causes other issues, there some some assumptions about it. So, I believe we should come back to this issue later and write noop unconditionally and fix other assumptions about it. That's the way to simplify this code I believe.

**Review by sjpotter — APPROVED** [review]

**Pull request merged**
