### PR TITLE
Adapt CMake for coverage changes.

### PR DESCRIPTION
**Pull request by yossigo**
* Build libraft.so to support tests.
* CMake target to create raft_cffi module.
* CMake changes to handle LD_LIBRARY_PATH for libraft.so to be found.
* raft_cffi_builder changes to support arbitrary include and library
  paths.

### CODE REVIEW

**Comment by tezc** [comment]
@yossigo Great! So, we can pass arguments to ffi. I've made some changes for CMake to prevent temp files out of the build directory, would you take a look? : 

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3819983..1ec9b91 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -27,7 +27,6 @@ endmacro()
 set(CMAKE_C_STANDARD 99)
 set(CMAKE_C_STANDARD_REQUIRED ON)
 set(CMAKE_C_EXTENSIONS OFF)
-set(BUILD_SHARED_LIBS ON)
 
 enable_testing()
 
@@ -64,32 +63,35 @@ add_custom_command(
         COMMAND lcov --list coverage.info --rc lcov_branch_coverage=1 --rc lcov_excl_br_line='assert'
 )
 
-add_dependencies(lib_coverage check)
+add_dependencies(lib_coverage check test_fuzzer test_virtraft)
 # ---------------------------- Code Coverage End ----------------------------- #
 
 
 # ------------------------------ Python Tests ---------------------------------#
+
+set(LIBPATH PYTHONPATH=${CMAKE_BINARY_DIR}/tests LD_LIBRARY_PATH=${CMAKE_BINARY_DIR})
+
 add_custom_target(test_fuzzer)
 add_custom_command(TARGET test_fuzzer
-                   COMMAND LD_LIBRARY_PATH=${CMAKE_BINARY_DIR} python ${CMAKE_SOURCE_DIR}/tests/log_fuzzer.py
-                    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
+                   COMMAND ${LIBPATH} python ${CMAKE_SOURCE_DIR}/tests/log_fuzzer.py
+                   WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
 add_dependencies(test_fuzzer raft_cffi)
 
 add_custom_target(test_virtraft)
 add_custom_command(TARGET test_virtraft
         WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
-        COMMAND LD_LIBRARY_PATH=${CMAKE_BINARY_DIR} python3 tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 1 -m 3 $(VIRTRAFT_OPTS)
-        COMMAND LD_LIBRARY_PATH=${CMAKE_BINARY_DIR} python3 tests/virtraft2.py --servers 7 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 1 -m 3 $(VIRTRAFT_OPTS)
-        COMMAND LD_LIBRARY_PATH=${CMAKE_BINARY_DIR} python3 tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 2 -m 3 $(VIRTRAFT_OPTS)
-        COMMAND LD_LIBRARY_PATH=${CMAKE_BINARY_DIR} python3 tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 3 -m 3 $(VIRTRAFT_OPTS)
-        COMMAND LD_LIBRARY_PATH=${CMAKE_BINARY_DIR} python3 tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 4 -m 3 $(VIRTRAFT_OPTS)
-        COMMAND LD_LIBRARY_PATH=${CMAKE_BINARY_DIR} python3 tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 5 -m 3 $(VIRTRAFT_OPTS)
-        COMMAND LD_LIBRARY_PATH=${CMAKE_BINARY_DIR} python3 tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 6 -m 3 $(VIRTRAFT_OPTS))
+        COMMAND ${LIBPATH} python3 ${CMAKE_SOURCE_DIR}/tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 1 -m 3 $(VIRTRAFT_OPTS)
+        COMMAND ${LIBPATH} python3 ${CMAKE_SOURCE_DIR}/tests/virtraft2.py --servers 7 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 1 -m 3 $(VIRTRAFT_OPTS)
+        COMMAND ${LIBPATH} python3 ${CMAKE_SOURCE_DIR}/tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 2 -m 3 $(VIRTRAFT_OPTS)
+        COMMAND ${LIBPATH} python3 ${CMAKE_SOURCE_DIR}/tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 3 -m 3 $(VIRTRAFT_OPTS)
+        COMMAND ${LIBPATH} python3 ${CMAKE_SOURCE_DIR}/tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 4 -m 3 $(VIRTRAFT_OPTS)
+        COMMAND ${LIBPATH} python3 ${CMAKE_SOURCE_DIR}/tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 5 -m 3 $(VIRTRAFT_OPTS)
+        COMMAND ${LIBPATH} python3 ${CMAKE_SOURCE_DIR}/tests/virtraft2.py --servers 5 -i 20000 --compaction_rate 50 --drop_rate 5 -P 10 --seed 6 -m 3 $(VIRTRAFT_OPTS))
 add_dependencies(test_virtraft raft_cffi)
 
 add_custom_target(raft_cffi)
 add_custom_command(TARGET raft_cffi
-                   COMMAND python3 ${CMAKE_SOURCE_DIR}/tests/raft_cffi_builder.py --libdir ${CMAKE_BINARY_DIR} --includedir ${CMAKE_SOURCE_DIR}/include
+                   COMMAND python3 ${CMAKE_SOURCE_DIR}/tests/raft_cffi_builder.py --libdir ${CMAKE_BINARY_DIR} --includedir ${CMAKE_SOURCE_DIR}/include --tmpdir ${CMAKE_BINARY_DIR}/
                    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
 # ----------------------------- Python Tests End ----------------------------- #
 
@@ -98,7 +100,7 @@ add_custom_command(TARGET raft_cffi
 add_custom_target(tests_full)
 add_dependencies(tests_full check test_fuzzer test_virtraft)
 
-add_library(raft
+add_library(raft SHARED
         src/raft_log.c
         src/raft_server.c
         src/raft_node.c
diff --git a/tests/raft_cffi_builder.py b/tests/raft_cffi_builder.py
index 944a9ce..1c25813 100644
--- a/tests/raft_cffi_builder.py
+++ b/tests/raft_cffi_builder.py
@@ -12,6 +12,7 @@ if __name__ == '__main__':
     parser = argparse.ArgumentParser()
     parser.add_argument('--libdir', type=str, default='.')
     parser.add_argument('--includedir', type=str, default='include')
+    parser.add_argument('--tmpdir', type=str, default='.')
     args = parser.parse_args()
 
     ffibuilder = cffi.FFI()
@@ -58,4 +59,4 @@ if __name__ == '__main__':
     ffibuilder.cdef('void *raft_entry_getdata(raft_entry_t *);')
     ffibuilder.cdef('raft_entry_t **raft_entry_array_deepcopy(raft_entry_t **src, int len);')
 
-    ffibuilder.compile(verbose=True)
+    ffibuilder.compile(tmpdir=args.tmpdir, verbose=True)
```

**Comment by yossigo** [comment]
@tezc LGTM, can you push these as a commit to this PR?

**Comment by tezc** [comment]
@yossigo Added as commit

**Review by tezc — DISMISSED** [review]

**Comment by yossigo** [comment]
@tezc Why did you remove `BUILD_SHARED_LIBS`? Using `SHARED` explicitly ends up creating only a shared library. IIUC you need to create two different targets for shared and static, unless `BUILD_SHARED_LIBS` is used.

**Comment by tezc** [comment]
@yossigo Sorry, I misinterpreted your intentions. I've made another commit : 
- Default build is static (Shared lib is such a waste for that small code base anyway)
- Users can still use `BUILD_SHARED_LIBS` if they want
- `cffi` builds still work for regular builds or coverage builds.

Are you ok with this?

**Comment by yossigo** [comment]
@tezc Why do you think it's a waste? We build both, the user can choose static or shared when linking.
The problem with the last commit is that `make tests_full` will be broken for non-Coverage builds. We can decide to always build shared with a different name (and then change the Makefile as well to be consistent) but I think it's generally a common practice to build both and let the user choose.

**Comment by tezc** [comment]
@yossigo 

> Why do you think it's a waste?

Shared linking disables compiler optimizations, has extra function call overhead, needs to be carried along with the executable etc. So, I like when libraries default build is static. Not a big deal though, just when you need to choose one as default, I'd go with static as a personal preference

> The problem with the last commit is that make tests_full will be broken for non-Coverage builds.

How ? It's running fine on my local.

> I think it's generally a common practice to build both and let the user choose.

But when you set BUILD_SHARED_LIBS ON, you don't build both. It just builds SHARED lib. If you don't set it, it builds STATIC(default). Your commit won't build shared and static at the same time. Cmake does not allow building static and shared at the same time with the same name ( Because Windows does not allow that so Cmake follows that rule to be portable). 

Your commit was making shared default, I've just changed it to static with my last commit. Users can still control it with BUILD_SHARED_LIBS flag.

I don't have any strong opinions on this. We might even force building both libs with the same name. (Add one build as another target, raft_shared, after build, rename the file etc. (But IIUC that target won't be usable by cmake users when they import the library).

**Comment by yossigo** [comment]
> How ? It's running fine on my local.

It did not build a shared library by default, make it worked if you built one previously and did not clean it up.

I've pushed a commit that follows the mentioned option 2, since I think it follows CMake convention more closely. Note that the Makefile still builds both static and shared always, and generates PIC code for both (and apparently this was the case always). Perhaps we should just adopt CMake as the only build option.

**Review by tezc — APPROVED** [review]

**Pull request merged**
